name: Extract Metadata with CS Tools
on:
  workflow_dispatch:
    inputs:
      cs_tools_version:
        description: "The CS Tools version to target for a manual run."
        required: false
        type: string
  schedule:
    # Runs every day at 5:20 AM UTC
    - cron: "20 5 * * *"

jobs:
  extract_data_from_thoughtspot:
    runs-on: ubuntu-latest
    env:
      # CS TOOLS IS COMMAND LINE LIBRARY WRAPPING TS APIS
      # https://thoughtspot.github.io/cs_tools/
      CS_TOOLS_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.cs_tools_version || 'v1.6.0' }}
      CS_TOOLS_THOUGHTSPOT__URL: ${{ secrets.THOUGHTSPOT_URL }}
      CS_TOOLS_THOUGHTSPOT__USERNAME: ${{ secrets.THOUGHTSPOT_USERNAME }}
      CS_TOOLS_THOUGHTSPOT__SECRET_KEY: ${{ secrets.THOUGHTSPOT_SECRET_KEY }}
      #P8_KEY_PATH: "github/tools_key.p8"
    
    steps:
      # SETUP PYTHON
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify Python version
      
      # UPDATE PIP
      - name: Ensure pip is up to date
        run: python -m pip install --upgrade pip
      
      # INSTALL A SPECIFIC VERSION OF cs_tools
      - name: Install CS Tools
        run: python -m pip install "cs_tools[cli] @ https://github.com/thoughtspot/cs_tools/archive/${{ env.CS_TOOLS_VERSION }}.zip"
      
      # ENSURE SYNCER DEPENDENCIES ARE INSTALLED
      - name: Install Snowflake dependencies
        run: python -m pip install "snowflake-sqlalchemy >= 1.6.1"

      - name: Create private key file
        run: |
          echo "${{ secrets.PRIVATE_KEY_PATH }}" > /tmp/snowflake_key.p8
          chmod 600 /tmp/snowflake_key.p8

      - name: Use the file path
        run: |
          echo "The file is located at: $TEST_FILE_PATH"
          cat $TEST_FILE_PATH

      - name: Set file path as environment variable
        run: echo "TEST_FILE_PATH=/tmp/snowflake_key.p8" >> $GITHUB_ENV
      
      # BUILD SYNCER CONNECTION STRING
      - name: Set Snowflake connection string
        run: |
          echo "DECLARATIVE_SYNCER_SYNTAX=account_name=${{ secrets.SNOWFLAKE_ACCOUNT }}&username=${{ secrets.SNOWFLAKE_USERNAME }}&secret=${{ secrets.SNOWFLAKE_PASSWORD }}&warehouse=${{ secrets.WAREHOUSE }}&role=${{ secrets.ROLE }}&database=${{ secrets.DATABASE }}&schema=${{ secrets.SNOWFLAKE_SCHEMA }}&authentication=key-pair&private_key_path=$TEST_FILE_PATH" >> $GITHUB_ENV
      
      # RUNS THE searchable metadata COMMAND
      - name: Refresh Metadata from ThoughtSpot
        run: >-
          cs_tools tools
          searchable metadata
          --syncer 'snowflake://${{ env.DECLARATIVE_SYNCER_SYNTAX }}&load_strategy=TRUNCATE'
          --config ENV:
      
      # CLEANUP
      - name: Clean up sensitive files
        if: always()
        run: rm -f ${{ env.P8_KEY_PATH }}
